# Generated by Django 6.1.1 on 2026-09-22 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdnanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_role', models.CharField(choices=[('senior_pharmacist', 'Senior Pharmacist'), ('ot_officer', 'OT Consumables Officer'), ('store_manager', 'Central Store Manager')], max_length=50)),
                ('dispensary_counter', models.CharField(choices=[('counter_1', 'Counter 1 - OPD Pharmacy'), ('counter_2', 'Counter 2 - IPD Pharmacy'), ('ot_supply', 'OT Supply Depot')], max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
