# Generated by Django 6.1.1 on 2026-09-22 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuhulProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_role', models.CharField(choices=[('Cashier', 'Cashier'), ('Accounts Supervisor', 'Accounts Supervisor'), ('Zakat Relief Officer', 'Zakat Relief Officer'), ('Pharmacy Cashier', 'Pharmacy Cashier')], max_length=50)),
                ('assigned_counter', models.CharField(max_length=100)),
                ('discount_approval_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ruhul_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
