# Generated by Django 6.1.1 on 2026-09-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_ruhul', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruhulprofile',
            name='assigned_counter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ruhulprofile',
            name='discount_approval_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ruhulprofile',
            name='finance_role',
            field=models.CharField(choices=[('Cashier', 'Cashier'), ('Accounts Supervisor', 'Accounts Supervisor'), ('Zakat Relief Officer', 'Zakat Relief Officer'), ('Pharmacy Cashier', 'Pharmacy Cashier')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ruhulprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruhul_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
