# Generated by Django 6.1.1 on 2026-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patient_mrn', models.CharField(max_length=50)),
                ('concession_type', models.CharField(choices=[('ZAKAT', 'Zakat Welfare Fund'), ('POOR', 'Poor Patient Relief'), ('STAFF', 'Staff Dependent'), ('EXECUTIVE', 'Executive Exemption')], max_length=30)),
                ('bill_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hospital_branch', models.CharField(max_length=100)),
                ('counter_name', models.CharField(choices=[('OPD', 'OPD Cash Counter'), ('OT', 'OT Surgery Packages'), ('PHARMACY', 'Eye Pharmacy'), ('OPTICAL', 'Optical Frame Shop'), ('DIAGNOSTICS', 'Diagnostics Counter')], max_length=30)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mfs_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
