# Generated by Django 6.1.1 on 2026-09-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionrecord',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
