# Generated by Django 6.1.1 on 2026-09-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reports', '0003_concessionrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='counter_name',
            field=models.CharField(choices=[('OPD', 'OPD Cash Counter'), ('OT', 'OT Surgery Packages'), ('PHARMACY', 'Eye Pharmacy'), ('OPTICAL', 'Optical Frame Shop'), ('DIAGNOSTICS', 'Diagnostics Counter')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='hospital_branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='mfs_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
