# Generated by Django 6.1.1 on 2026-09-26 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reports', '0005_concessionrecord_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
