# Generated by Django 6.1.1 on 2026-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reports', '0006_alter_concessionrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycollection',
            name='hospital_branch',
            field=models.CharField(default='Ispahani Islamia Eye Institute and Hospital', max_length=100, null=True),
        ),
    ]
