# Generated by Django 6.1.1 on 2026-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reports', '0007_alter_dailycollection_hospital_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionrecord',
            name='bill_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='concessionrecord',
            name='concession_type',
            field=models.CharField(choices=[('ZAKAT', 'Zakat Welfare Fund'), ('POOR', 'Poor Patient Relief'), ('STAFF', 'Staff Dependent'), ('EXECUTIVE', 'Executive Exemption')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='concessionrecord',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='concessionrecord',
            name='patient_mrn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='concessionrecord',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
