# Generated by Django 6.1.1 on 2026-09-22 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NusratProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_counter', models.CharField(help_text='Example: Registration Counter 2 - Glaucoma Desk', max_length=100)),
                ('shift', models.CharField(choices=[('morning', 'Morning (8 AM - 2 PM)'), ('evening', 'Evening (2 PM - 8 PM)'), ('night', 'Night Emergency')], default='morning', max_length=20)),
                ('desk_extension', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
