# Generated by Django 6.1.1 on 2026-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDispensingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hospital_branch', models.CharField(max_length=100)),
                ('patient_mrn', models.CharField(max_length=50)),
                ('medicine_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('anti_glaucoma', 'Anti-Glaucoma'), ('antibiotic', 'Antibiotic'), ('steroid', 'Steroid'), ('lubricant', 'Lubricant'), ('surgical_consumable', 'Surgical Consumable')], max_length=50)),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('batch_number', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalConsumableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('subspecialty', models.CharField(choices=[('cataract', 'Cataract'), ('vitreo_retina', 'Vitreo-Retina'), ('glaucoma', 'Glaucoma'), ('cornea', 'Cornea')], max_length=50)),
                ('current_quantity', models.PositiveIntegerField()),
                ('reorder_threshold', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
