# Generated by Django 6.1.1 on 2026-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOPDCensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hospital_branch', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(choices=[('General Eye OPD', 'General Eye OPD'), ('Cornea Clinic', 'Cornea Clinic'), ('Retina Clinic', 'Retina Clinic'), ('Glaucoma Clinic', 'Glaucoma Clinic'), ('Pediatric Clinic', 'Pediatric Clinic'), ('Emergency Eye Care', 'Emergency Eye Care')], max_length=50)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('new_patients', models.PositiveIntegerField(default=0)),
                ('followup_patients', models.PositiveIntegerField(default=0)),
                ('refractions_done', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IPDBedOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hospital_branch', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('Male Surgical Ward', 'Male Surgical Ward'), ('Female Surgical Ward', 'Female Surgical Ward'), ('VIP Cabin', 'VIP Cabin'), ('Daycare Cataract Recovery', 'Daycare Cataract Recovery')], max_length=50)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('new_admissions', models.PositiveIntegerField(default=0)),
                ('discharges_today', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
