# Generated by Django 6.1.1 on 2026-09-22 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of Surgery (YYYY-MM-DD)')),
                ('patient_mrn', models.CharField(help_text='Medical Record Number (MRN) of the Patient', max_length=8, unique=True)),
                ('patient_name', models.CharField(help_text='Full Name of the Patient', max_length=100)),
                ('patient_age', models.PositiveIntegerField(help_text='Age of the Patient')),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender of the Patient', max_length=10)),
                ('eye', models.CharField(choices=[('LE', 'Left Eye'), ('RE', 'Right Eye'), ('BE', 'Both Eyes')], help_text='Which eye was operated on', max_length=2)),
                ('surgery_type', models.CharField(choices=[('Cataract', 'Cataract'), ('Glaucoma', 'Glaucoma'), ('Retina', 'Retina'), ('Cornea', 'Cornea'), ('Corneal', 'Corneal'), ('LASIK', 'LASIK'), ('Oculoplastic', 'Oculoplastic'), ('Pediatric Ophthalmology', 'Pediatric Ophthalmology'), ('Neuro-Ophthalmology', 'Neuro-Ophthalmology'), ('Uveitis', 'Uveitis'), ('Refractive Surgery', 'Refractive Surgery'), ('Other', 'Other')], help_text='Type of Surgery Performed', max_length=50)),
                ('surgeon_name', models.CharField(help_text='Name of the Surgeon', max_length=100)),
                ('ot_room', models.CharField(choices=[('OT-1', 'OT Room 1 (General OT)'), ('OT-2', 'OT Room 2 (Retina OT)'), ('OT-3', 'OT Room 3 (Laser OT)'), ('OT-4', 'OT Room 4 (Pediatric OT)')], help_text='Operating Theater Room', max_length=10)),
                ('outcome', models.CharField(choices=[('Successful', 'Successful'), ('Under Observation', 'Under Observation'), ('Complications', 'Complications')], help_text='Outcome of the Surgery', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional Notes or Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
