# Generated by Django 6.1.1 on 2026-09-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_naimul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of Diagnosis (YYYY-MM-DD)')),
                ('patient_mrn', models.CharField(help_text='Medical Record Number (MRN) of the Patient', max_length=8, unique=True)),
                ('eye', models.CharField(choices=[('LE', 'Left Eye'), ('RE', 'Right Eye'), ('BE', 'Both Eyes')], help_text='Which eye was diagnosed', max_length=2)),
                ('procedure_name', models.CharField(choices=[('OCT Macula', 'OCT Macula'), ('OCT RNFL', 'OCT RNFL'), ('Visual Field (Perimetry)', 'Visual Field (Perimetry)'), ('B-Scan', 'B-Scan'), ('FFA', 'FFA'), ('Other', 'Other')], help_text='Procedure Performed', max_length=50)),
                ('technician_name', models.CharField(help_text='Name of the Technician', max_length=100)),
                ('findings_summary', models.TextField(blank=True, help_text='Findings summary from the Diagnosis')),
            ],
        ),
    ]
