# Generated by Django 6.1.1 on 2026-09-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_naimul', '0002_diagnosisrecord'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='DoctorProfile',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #         ],
    #     ),
    #     migrations.RenameModel(
    #         old_name='DiagnosisRecord',
    #         new_name='DiagnosisProcedure',
    #     ),
    # ]
    
    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
