# Generated by Django 6.1.1 on 2026-09-23 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_naimul', '0002_diagnosisrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_mrn', models.CharField(help_text='Medical Record Number (MRN)', max_length=12)),
                ('patient_name', models.CharField(help_text='Full Name of the Patient', max_length=100)),
                ('patient_phone', models.CharField(blank=True, help_text='Patient Contact Number', max_length=20)),
                ('patient_age', models.PositiveIntegerField(help_text='Age of the Patient')),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender', max_length=10)),
                ('appointment_type', models.CharField(choices=[('Pre-Op Surgical Workup', 'Pre-Op Surgical Workup'), ('Consultant Clinic', 'Consultant Clinic'), ('Post-Op Follow-Up', 'Post-Op Follow-Up Visit'), ('Diagnostic Scan', 'Diagnostic Scan (OCT / B-Scan / VF)'), ('OT Anesthesia Clearance', 'OT Anesthesia Clearance'), ('Emergency Consultation', 'Emergency Consultation'), ('Corneal Topography', 'Corneal Topography / Biometry'), ('Refraction & Prescription', 'Refraction & Spectacle Prescription')], default='Consultant Clinic', help_text='Type of clinical appointment', max_length=60)),
                ('doctor_name', models.CharField(help_text='Assigned Consultant / Doctor', max_length=100)),
                ('appointment_date', models.DateField(help_text='Date of the Appointment (YYYY-MM-DD)')),
                ('appointment_time_slot', models.CharField(choices=[('08:00 - 09:00 AM', '08:00 - 09:00 AM (Morning First)'), ('09:00 - 10:00 AM', '09:00 - 10:00 AM (Morning Regular)'), ('10:00 - 11:00 AM', '10:00 - 11:00 AM (Mid-Morning)'), ('11:00 - 12:00 PM', '11:00 - 12:00 PM (Late Morning)'), ('12:00 - 01:00 PM', '12:00 - 01:00 PM (Early Afternoon)'), ('02:00 - 03:00 PM', '02:00 - 03:00 PM (Afternoon)'), ('03:00 - 04:00 PM', '03:00 - 04:00 PM (Late Afternoon)'), ('04:00 - 05:00 PM', '04:00 - 05:00 PM (Evening Clinic)')], default='09:00 - 10:00 AM', help_text='Time slot for the appointment', max_length=30)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show')], default='Scheduled', help_text='Current status of the appointment', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Clinical notes, referral details, or special requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who created the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of Diagnosis (YYYY-MM-DD)')),
                ('patient_mrn', models.CharField(help_text='Medical Record Number (MRN) of the Patient', max_length=8, unique=True)),
                ('eye', models.CharField(choices=[('LE', 'Left Eye'), ('RE', 'Right Eye'), ('BE', 'Both Eyes')], help_text='Which eye was diagnosed', max_length=2)),
                ('procedure_name', models.CharField(choices=[('OCT Macula', 'OCT Macula'), ('OCT RNFL', 'OCT RNFL'), ('Visual Field (Perimetry)', 'Visual Field (Perimetry)'), ('B-Scan', 'B-Scan'), ('FFA', 'FFA'), ('Other', 'Other')], help_text='Procedure Performed', max_length=50)),
                ('technician_name', models.CharField(help_text='Name of the Technician', max_length=100)),
                ('findings_summary', models.TextField(blank=True, help_text='Findings summary from the Diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='NaimulProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Surgeon', 'Surgeon'), ('Technician', 'Technician'), ('Consultant', 'Consultant Eye Surgeon'), ('Associate', 'Associate Specialist'), ('Resident', 'Surgical Resident / Fellow'), ('OT Nurse', 'OT Nursing Supervisor'), ('Staff', 'OT Coordinator / Surgical Staff'), ('Admin', 'Admin'), ('Other', 'Other')], default='Consultant', max_length=30)),
                ('specialty', models.CharField(choices=[('Cataract', 'Cataract & Refractive'), ('Glaucoma', 'Glaucoma Services'), ('Retina', 'Vitreoretinal Surgery'), ('Cornea', 'Cornea & External Disease'), ('Oculoplastic', 'Oculoplastic  & Orbit'), ('Pediatric Ophthalmology', 'Pediatric Ophthalmology & Strabismus'), ('Neuro-Ophthalmology', 'Neuro-Ophthalmology'), ('Uveitis', 'Uveitis Services'), ('Refractive Surgery', 'Refractive Surgery'), ('Other', 'Other')], default='Cataract', max_length=50)),
                ('assigned_ot_room', models.CharField(choices=[('OT-1', 'OT Room 1 (General OT)'), ('OT-2', 'OT Room 2 (Retina OT)'), ('OT-3', 'OT Room 3 (Laser OT)'), ('OT-4', 'OT Room 4 (Pediatric OT)')], default='OT-1', max_length=20)),
                ('surgeon_code', models.CharField(default='SURG-101', help_text='Hospital Surgeon ID Code', max_length=30)),
                ('license_number', models.CharField(default='BMDC-A-48291', help_text='Medical Council License Number', max_length=50)),
                ('department', models.CharField(default='Department of Ophthalmology & Microsurgery', max_length=100)),
                ('phone', models.CharField(blank=True, default='+880 1711-000000', max_length=20)),
                ('bio', models.TextField(blank=True, default='Consultant Ophthalmic Surgeon specializing in advanced micro-incision cataract surgery and anterior segment reconstruction.')),
                ('can_view_patient_details', models.BooleanField(default=True, help_text='Doctor Role Permission: View Patient Demographics & Records')),
                ('can_view_medical_history', models.BooleanField(default=True, help_text='Doctor Role Permission: View Patient Medical History & Diagnostic Scans')),
                ('can_view_ot_slots', models.BooleanField(default=True, help_text='Doctor Role Permission: View Operation Theatre Slot Schedules')),
                ('can_apply_surgery', models.BooleanField(default=True, help_text='Staff Role Permission: Submit Surgery Applications & Book OT Slots')),
                ('can_make_appointments', models.BooleanField(default=True, help_text='Staff Role Permission: Schedule & Manage Patient Appointments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='naimul_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DiagnosisRecord',
        ),
        migrations.AddField(
            model_name='surgeryrecord',
            name='medical_history',
            field=models.TextField(blank=True, help_text="Patient's Medical History and Previous Surgeries"),
        ),
        migrations.AddField(
            model_name='surgeryrecord',
            name='ot_slot',
            field=models.CharField(blank=True, choices=[('Slot 1 (08:30 - 10:00 AM)', 'Slot 1 (08:30 - 10:00 AM) - Morning Primary'), ('Slot 2 (10:15 - 11:45 AM)', 'Slot 2 (10:15 - 11:45 AM) - Mid-Day Micro-Surgery'), ('Slot 3 (12:00 - 01:30 PM)', 'Slot 3 (12:00 - 01:30 PM) - Afternoon Session'), ('Slot 4 (02:00 - 03:30 PM)', 'Slot 4 (02:00 - 03:30 PM) - Post-Lunch Refractive'), ('Emergency Slot', 'Emergency / Add-on Slot')], help_text='Operating Theater Slot', max_length=30, null=True),
        ),
    ]
