# Generated by Django 6.1.1 on 2026-09-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_naimul', '0003_appointment_diagnosisprocedure_naimulprofile_and_more'),
        ('users_naimul', '0003_doctorprofile_and_more'),
    ]

    operations = [
    ]
