# Generated by Django 6.1.1 on 2026-09-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_naimul', '0004_merge_20260926_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.AlterField(
            model_name='naimulprofile',
            name='role',
            field=models.CharField(choices=[('Surgeon', 'Surgeon'), ('Technician', 'Technician'), ('Consultant', 'Consultant Eye Surgeon'), ('Associate', 'Associate Specialist'), ('Resident', 'Surgical Resident / Fellow'), ('OT Nurse', 'OT Nursing Supervisor'), ('Staff', 'OT Coordinator / Surgical Staff'), ('Admin', 'Admin'), ('Other', 'Other')], default='Surgeon', max_length=30),
        ),
    ]
